version: '3.9'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass..'
      MYSQL_PASSWORD: 'pass..'
      MYSQL_DATABASE: 'db-prueba'
      MYSQL_USER: 'Enoc'
    expose:
      - 3311
    ports:
      - "3311:3306"
    volumes:
       - ./data:/var/lib/mysql